name: 编译巴法云stdoutsubc
on:
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
jobs:
  build:
    name: Build ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - target: aarch64-linux-musl
          URL: aarch64-linux-musl
          
        - target: x86_64-linux-musl
          URL: x86_64-linux-musl
            
        - target: i686-linux-musl
          URL: i686-linux-musl
        
        - target: armv7-linux-musleabihf
          URL: armv7l-linux-musleabihf

        - target: armv7-linux-musleabi
          URL: armv7m-linux-musleabi
          
        - target: arm-linux-musleabihf
          URL: arm-linux-musleabihf

        - target: arm-linux-musleabi
          URL: arm-linux-musleabi

        - target: mipsel-linux-musl
          URL: mipsel-linux-muslsf

        - target: mips-linux-musl
          URL: mips-linux-muslsf

    runs-on: ubuntu-latest
    steps:
    
     - name: Checkout code
       uses: actions/checkout@v4
       
     - name: 下载gcc
       uses: lmq8267/dl-musl@main
       with:
        target: ${{ matrix.URL }}
        static: true
        gccpath: /tmp
        
     - name: 安装 UPX
       uses: crazy-max/ghaction-upx@v3
       with:
        version: latest
        install-only: true
        
     - name: 编译
       run: |
         mkdir -p build && cd build
         export CC="$CC -static"
         export CXX="$CXX -static"
         cmake ..
         make
         
         mkdir -p /opt/bin
         cp -f MQTTPacket/samples/pub0sub1_nb /opt/bin/stdoutpub
         cp -f MQTTClient-C/samples/linux/stdoutsubc /opt/bin/
         cp -f MQTTClient/samples/linux/stdoutsub /opt/bin/
         file /opt/bin/stdoutsubc 
         $STRIP /opt/bin/*
         file /opt/bin/stdoutsubc
         upx --lzma --best /opt/bin/*
         
     - uses: actions/upload-artifact@v4
       with:
        name: stdoutsubc-${{ matrix.target }}
        path: /opt/bin/*
